spring.application.name=studytracker-backend
spring.datasource.url=jdbc:postgresql://ep-fragrant-fog-a59chb0x-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_DrIukX3CZ8QG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
